enviroments:
  default: local
  local:
    name: 'Localhost'
    url: 'http://ufrvpndev/'
  grid:
    name: 'Local grid'
    url: 'http://ufrvpndev/'
    hub_url: "http://localhost:4444/wd/hub"
  dev:
    name: 'Devstand No CI'
    url: 'http://ufrvpndev/'
  development:
    name: 'Devstand CI'
    url: 'http://ufrvpndev/'
    hub_url: "http://ufrjens1:4445//wd/hub"
  integration:
    name: 'Integration CI'
    url: 'http://ufrtest/'
    hub_url: "http://ufrvpndevjens1:4445/wd/hub"
  prelive:
    name: 'Prelive CI'
    url: 'http://ufrappint4/'
    hub_url: "http://ufrvpndevjens1:4445/wd/hub"

browser:
  window:
    height: 1280
    width: 1024

capybara:
  default_max_wait_time: 20



